"""telegram user model

Revision ID: 3fdad362bda0
Revises: 
Create Date: 2025-05-14 20:32:29.357822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fdad362bda0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tg_username', sa.String(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=True)
    op.create_index(op.f('ix_user_tg_username'), 'user', ['tg_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tg_username'), table_name='user')
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
