"""telegram_user_model

Revision ID: ad866b1f97d0
Revises: 
Create Date: 2025-06-17 06:41:26.096577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad866b1f97d0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tg_username', sa.String(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_users_tg_id'), 'telegram_users', ['tg_id'], unique=True)
    op.create_index(op.f('ix_telegram_users_tg_username'), 'telegram_users', ['tg_username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_users_tg_username'), table_name='telegram_users')
    op.drop_index(op.f('ix_telegram_users_tg_id'), table_name='telegram_users')
    op.drop_table('telegram_users')
    # ### end Alembic commands ###
