services:
  backend:
    build:
      context: ..
      dockerfile: docker/images/backend.Dockerfile
    env_file:
      - ../services/backend/envs/dev.env
    ports:
      - "9000:8000"
    depends_on:
      - postgres
    volumes:
      - ../services/backend:/service
  frontend:
    build:
      context: ..
      dockerfile: docker/images/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../services/frontend:/service
      - node_modules:/service/node_modules
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: conote
      POSTGRES_PASSWORD: conote
      POSTGRES_DB: conote
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U conote -d conote" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules: